In [6]:
import numpy as np

#a)
a = np.linspace(0, 1, num=11, dtype=float)
print(a)

#b)
b = np.zeros((5,6), dtype='b')
print(b)

#c
x = np.array([0,1,2,3,4,5,6,7,8], dtype=complex)
c = 4 ** x
print(c)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[1.0000e+00+0.j 4.0000e+00+0.j 1.6000e+01+0.j 6.4000e+01+0.j
 2.5600e+02+0.j 1.0240e+03+0.j 4.0960e+03+0.j 1.6384e+04+0.j
 6.5536e+04+0.j]
