In [4]:
import numpy as np

#a)
v1 = np.array([3, 5, 6, 8, 12, 14, 24, 26])
print(v1)

#b)
v2 = v1[1::2]
print(v2)

#c)
v3 = v1[::-1]
print(v3)

[ 3  5  6  8 12 14 24 26]
[ 5  8 14 26]
[26 24 14 12  8  6  5  3]
